const itemList = [
  {
    id: 1,
    category: "Legs",
    name: "Camouflage Military Shorts",
    price: 34.99,
    color: "Green",
    description:
      "Durable and stylish military-style shorts designed for comfort and flexibility during outdoor activities.",
    image: "./images/MilitaryShorts.png",
    availableSizes: ["M", "L"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },

  {
    id: 2,
    category: "Shoes",
    name: "Timberland Boots",
    price: 89.99,
    color: "White",
    description:
      "Classic white Timberland boots designed for style and function, perfect for every occasion.",
    image: "./images/WhiteTimbs.png",
    availableSizes: ["L", "XL"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: 3,
    category: "Head",
    name: "Fiesta Sombrero",
    price: 29.99,
    color: "Multicolored",
    description:
      "Authentic Mexican sombrero, perfect for adding a festive and vibrant touch to your wardrobe.",
    image: "./images/MexicanHat.png",
    availableSizes: ["M", "XL"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: 4,
    category: "Torso",
    name: "Sky Blue Shirt",
    price: 24.99,
    color: "Blue",
    description:
      "A versatile sky blue shirt that adds a relaxed yet stylish look to your everyday wardrobe.",
    image: "./images/BlueShirt.png",
    availableSizes: ["M", "L", "XL"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: 5,
    category: "Torso",
    name: "Crimson Sweater",
    price: 39.99,
    color: "Red",
    description:
      "A stylish crimson red sweater designed to keep you warm and fashionable during colder days.",
    image: "./images/RedSweater.png",
    availableSizes: ["L", "XL"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: 6,
    category: "Head",
    name: "Aqua Scarf",
    price: 19.99,
    color: "Blue",
    description:
      "A classic aqua blue scarf made from soft cashmere fabric, perfect for adding an elegant touch to any outfit.",
    image: "./images/BlueScarf.png",
    availableSizes: ["M", "L"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: 7,
    category: "Legs",
    name: "Ocean Blue Shorts",
    price: 39.99,
    color: "Blue",
    description:
      "Comfortable and breathable ocean blue shorts, perfect for relaxing days and outdoor adventures.",
    image: "./images/BlueShorts.png",
    availableSizes: ["M", "XL"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: 8,
    category: "Shoes",
    name: "Espresso Brown Shoes",
    price: 19.99,
    color: "Brown",
    description:
      "Classic brown shoes designed for both style and comfort, ideal for any occasion.",
    image: "./images/BrownShoes.png",
    availableSizes: ["M", "L"],
    allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  // {
  //   id: 9,
  //   category: "Shoes",
  //   name: "Midnight Converse",
  //   price: 29.99,
  //   color: "Black",
  //   description:
  //     "Sleek black Converse shoes with a minimalist design, perfect for creating a stylish, everyday look.",
  //   image: "./images/BlackConverse.png",
  //   availableSizes: ["S", "M", "L"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 10,
  //   category: "Torso",
  //   name: "Charcoal Grey Hoodie",
  //   price: 49.99,
  //   color: "Grey",
  //   description:
  //     "A comfortable charcoal grey hoodie designed for warmth and casual style, perfect for colder days.",
  //   image: "./images/GreyHoodie.png",
  //   availableSizes: ["M", "L", "XL"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 11,
  //   category: "Legs",
  //   name: "Steel Grey Pants",
  //   price: 34.99,
  //   color: "Grey",
  //   description:
  //     "Stylish grey pants designed for versatility and comfort, perfect for both formal and casual wear.",
  //   image: "./images/GreyPants.png",
  //   availableSizes: ["M", "L", "XL"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 12,
  //   category: "Torso",
  //   name: "Classic Black T-shirt",
  //   price: 14.99,
  //   color: "Black",
  //   description:
  //     "A basic black t-shirt that offers a timeless, versatile style for any casual outfit.",
  //   image: "./images/BlackTshirt.png",
  //   availableSizes: ["S", "M", "L"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 13,
  //   category: "Legs",
  //   name: "Elegant Classy Pants",
  //   price: 49.99,
  //   color: "Various",
  //   description:
  //     "Elegant trousers that combine style and sophistication, perfect for formal occasions and events.",
  //   image: "./images/ClassyPants.png",
  //   availableSizes: ["M", "L", "XL"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 14,
  //   category: "Head",
  //   name: "Crimson Hat",
  //   price: 14.99,
  //   color: "Red",
  //   description:
  //     "A vibrant Crimson Hat designed to complete your casual look with style and flair.",
  //   image: "./images/RedHat.png",
  //   availableSizes: ["M", "L"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 15,
  //   category: "Shoes",
  //   name: "Azure Blue Shoes",
  //   price: 59.99,
  //   color: "Blue",
  //   description:
  //     "Stylish azure blue shoes that add a pop of color and personality to your casual outfits.",
  //   image: "./images/BlueShoes.png",
  //   availableSizes: ["M", "L"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 16,
  //   category: "Head",
  //   name: "Sky Blue Hat",
  //   price: 19.99,
  //   color: "Blue",
  //   description:
  //     "A classic sky blue hat designed to complement your look with subtle elegance.",
  //   image: "./images/BlueHat.png",
  //   availableSizes: ["M", "L"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 17,
  //   category: "Legs",
  //   name: "Chestnut Brown Pants",
  //   price: 39.99,
  //   color: "Brown",
  //   description:
  //     "Stylish brown pants that offer comfort and versatility for any casual or semi-formal occasion.",
  //   image: "./images/BrownPants.png",
  //   availableSizes: ["M", "L", "XL"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 18,
  //   category: "Head",
  //   name: "Cocoa Brown Hat",
  //   price: 19.99,
  //   color: "Brown",
  //   description:
  //     "A classic cocoa brown hat that adds a touch of sophistication and style to any look.",
  //   image: "./images/BrownHat.png",
  //   availableSizes: ["M", "L"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 19,
  //   category: "Shoes",
  //   name: "Golden Yellow Shoes",
  //   price: 49.99,
  //   color: "Yellow",
  //   description:
  //     "Vibrant yellow shoes that make a bold statement and add a burst of color to your outfit.",
  //   image: "./images/YellowShoes.png",
  //   availableSizes: ["M", "L"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
  // {
  //   id: 20,
  //   category: "Torso",
  //   name: "Rose Pink Hoodie",
  //   price: 34.99,
  //   color: "Pink",
  //   description:
  //     "A cozy rose pink hoodie that provides both comfort and a trendy style for chilly days.",
  //   image: "./images/PinkHoodie.png",
  //   availableSizes: ["M", "L", "XL"],
  //   allSizes: ["XS", "S", "M", "L", "XL", "XXL"],
  // },
];

export default itemList;
